### PR TITLE
Adding the facebook photo unique id to OLFacebookImage

### PR DESCRIPTION
**Pull request by jfradj**

### CODE REVIEW

**Comment by jfradj** [comment]
Thanks for accepting this.
I've just seen that you've accepted another request about the same feature addition before mine.
The pull request was relaying on [this](https://github.com/OceanLabs/FacebookImagePicker-iOS/blob/master/FacebookImagePicker/OLFacebookImage.m#L99) method, which isn't used anymore.

**Comment by kkarayannis** [comment]
I believe the other pull request implemented the same in a different way and used the `uid` variable. Does that not work for you?

**Comment by orenk86** [comment]
Hi, that pull request was mine. I have used a different property named photoId, and I noticed that it has been removed in the merges.

I can adapt my code and change the property name, but I believe that @jfradj 's code already offers the desired functionality...

**Comment by kkarayannis** [comment]
I've removed the unused method.

**Pull request merged**
